name: CI
on:
  pull_request:
  push:
    branches: main

jobs:
  tests:
    runs-on: ubuntu-20.04
    name: Test (${{matrix.elixir}}/${{matrix.otp}})

    strategy:
      matrix:
        otp: [23.x, 24.x, 25.x]
        elixir: [1.13.x, 1.14.x]

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          deps
        key: ${{ runner.os }}-mix-${{matrix.otp}}-${{matrix.elixir}}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{matrix.otp}}-${{matrix.elixir}}-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Run Tests
      run: mix test

  formatter:
    runs-on: ubuntu-latest
    name: Formatter (1.15.x/26.x)

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 26.x
        elixir-version: 1.15.x
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-23-1.14-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-23-1.14-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Run Formatter
      run: mix format --check-formatted
