name: Release tableau_new
on:
  push:
    branches:
      - main
    paths:
      - 'tableau_new/**/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tableau_new
    strategy:
      matrix:
        otp: [25.3]
        elixir: [1.14.x]
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: elixir
          path: ./tableau_new
          package-name: tableau_new
          bump-minor-pre-major: true

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/cache@v3
        id: cache
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Install Dependencies
        if: steps.release.outputs.release_created && steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: publish to hex
        if: ${{ steps.release.outputs.release_created }}
        env:
          HEX_API_KEY: ${{secrets.HEX_API_KEY}}
        run: |
          mix hex.publish --yes
